from google.adk.agents import Agent
from google.adk.tools.tool_context import ToolContext

def review_and_approve_response(generated_response: str, tool_context: ToolContext) -> dict:
    """
    Reviews a generated response for correctness, appropriateness, and politeness.
    This is a mandatory check before a response is sent to the user.

    Args:
        generated_response: The response text generated by another agent.
        tool_context: Context for accessing session state (e.g., for logging validation counts).

    Returns:
        A dictionary containing:
        - 'approved': boolean, True if the response is fine, False otherwise.
        - 'feedback': str, reasons for disapproval or suggestions for improvement if not approved.
                      Empty if approved.
    """
    print(f"--- Tool (validator_agent): review_and_approve_response called for: '{generated_response}' ---")

    approved = True
    feedback_points = []

    # Rule 1: Check for politeness (simplified)
    polite_keywords = ["please", "thank", "could you", "would you", "welcome", "happy to help"]
    negative_keywords = ["stupid", "idiot", "never", "obviously", "dumb"] # Keywords that might indicate rudeness or unhelpfulness

    is_polite_present = any(keyword in generated_response.lower() for keyword in polite_keywords)
    is_negative_present = any(keyword in generated_response.lower() for keyword in negative_keywords)

    if is_negative_present:
        approved = False
        feedback_points.append("Response contains potentially rude or unhelpful language.")
    elif not is_polite_present and len(generated_response.split()) > 5 : # Very short responses might not need explicit politeness
        # This is a soft check; not all responses need these.
        # Consider if this should make approved=False or just be a suggestion.
        # For now, let's make it a reason for disapproval if other checks also fail or if it's blatant.
        # For a stricter validation as per new requirement, let's make it a reason for disapproval.
        if not any(kw in generated_response.lower() for kw in ["joke", "reminder", "validated", "sorry", "unable"]): # Don't penalize simple statements of fact from tools
            approved = False
            feedback_points.append("Response could be more polite or engaging.")


    # Rule 2: Check for correctness (very basic placeholder)
    # In a real scenario, this would be much more complex, possibly involving fact-checking tools,
    # grammar checks, or domain-specific validation.
    if "[[ERROR]]" in generated_response or "NaN" in generated_response:
        approved = False
        feedback_points.append("Response contains technical error indicators.")

    # Rule 3: Check for appropriateness (placeholder)
    # e.g., not making promises it can't keep, not generating harmful content.
    # This would require more sophisticated checks, possibly another LLM call or specialized tools.
    if "I guarantee this will work" in generated_response:
        approved = False
        feedback_points.append("Response makes an unsupported guarantee.")

    if "absolutely sure" in generated_response.lower() and not "not absolutely sure" in generated_response.lower() :
        # Overconfidence can be an issue.
        # approved = False # Decided this might be too strict for now.
        # feedback_points.append("Response seems overconfident. Consider rephrasing with less certainty unless it's a direct quote or fact.")
        pass


    # Update validated responses count in state - this now counts how many times validation was ATTEMPTED
    current_count = tool_context.state.get("validated_responses_count", 0)
    tool_context.state["validated_responses_count"] = current_count + 1

    final_feedback = " ".join(feedback_points) if feedback_points else "Response approved."

    print(f"--- Validator Result: Approved: {approved}, Feedback: {final_feedback} ---")

    return {
        "action": "review_and_approve_response",
        "response_reviewed": generated_response,
        "approved": approved,
        "feedback": final_feedback if not approved else "", # Only provide feedback if not approved
    }

validator_agent = Agent(
    name="validator_agent",
    model="gemini-2.0-flash", # Can use a more capable model if complex review needed
    description="A mandatory review agent that checks all outgoing responses for correctness, politeness, and appropriateness before they are sent to the user.",
    instruction="""
    You are the Validator Agent. Your role is critical and NON-NEGOTIABLE.
    You MUST review every response generated by other agents before it goes to the user.
    Use the `review_and_approve_response` tool to perform this check.

    The tool will be called with the `generated_response` from another agent.
    Your task is to evaluate this response based on the rules embedded in the tool (politeness, correctness, appropriateness).
    The tool will return `approved: True` or `approved: False` and `feedback`.

    If the tool output indicates `approved: False`, the manager agent will attempt to have the original agent retry.
    Your output (from the tool) will be the definitive decision on whether a response is user-facing.
    Do not add conversational fluff around the tool call. Simply execute the tool with the provided response.
    The session state `validated_responses_count` tracks how many responses you have reviewed.
    """,
    tools=[review_and_approve_response],
)
